-- I really need to find a workaround for this, I don't think this is how I'm supposed to use this
local Spell     = LibStub:NewLibrary("Spell", 1)
local Unit      = LibStub:NewLibrary("Unit", 1)
local Buff      = LibStub:NewLibrary("Buff", 1)
local Debuff    = LibStub:NewLibrary("Debuff", 1)
local Group     = LibStub:NewLibrary("Group", 1)
local Player    = LibStub:NewLibrary("Player", 1)
local Rotation  = LibStub:NewLibrary("Rotation", 1)
local Utils     = LibStub:NewLibrary("Utils", 1)
local Events    = LibStub:NewLibrary("Events", 1)
local BossManager = LibStub:NewLibrary("BossManager", 1)
